#!/bin/bash

LIMINE_OUT=${1:-limine}

if [ ! -d "$LIMINE_OUT" ]; then
    git clone https://github.com/limine-bootloader/limine.git --branch=v8.x-binary --depth=1 "$LIMINE_OUT"
fi

if command -v make >/dev/null 2>&1; then
    make -C "$LIMINE_OUT"
else
    echo "make is not installed or not found in the system."
    exit 1
fi
