#!/bin/bash

cd "$(dirname "$(realpath "$0")")"

KERNEL_PATH="athix-kernel"

make build

if [[ ! -f "limine/limine" ]]; then
    echo "Limine is not found. Please build Limine first, expected limine in "limine/""
    exit 1
fi

ISO_ROOT="iso_root"
mkdir -p "$ISO_ROOT/boot/limine" "$ISO_ROOT/EFI/BOOT"

if [[ -f "$KERNEL_PATH" ]]; then
    cp -v "$KERNEL_PATH" "$ISO_ROOT/boot/"
else
    echo "Kernel file not found: $KERNEL_PATH"
    exit 1
fi

cp -v limine/limine-bios.sys "$ISO_ROOT/boot/limine/"
cp -v limine/limine-bios-cd.bin "$ISO_ROOT/boot/limine/"
cp -v limine/limine-uefi-cd.bin "$ISO_ROOT/boot/limine/"
cp -v limine/BOOTX64.EFI "$ISO_ROOT/EFI/BOOT/"
cp -v limine/BOOTIA32.EFI "$ISO_ROOT/EFI/BOOT/"
cp -v config/default_limine.conf "$ISO_ROOT/boot/limine/"

ISO_NAME="Athix-raw.iso"
xorriso -as mkisofs -b boot/limine/limine-bios-cd.bin \
    -no-emul-boot -boot-load-size 4 -boot-info-table \
    --efi-boot boot/limine/limine-uefi-cd.bin \
    -efi-boot-part --efi-boot-image --protective-msdos-label \
    "$ISO_ROOT" -o "$ISO_NAME"

rm -rf "$ISO_ROOT"
echo ">>> ISO created: $ISO_NAME"

echo ">>> Running kernel-only ISO"
qemu-system-x86_64 -name "Athix - raw" -cdrom "Athix-raw.iso" -boot d -machine q35 -rtc base=localtime,clock=host -m 2G -serial stdio "$@"
echo ">>> Finished running"